from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

from fem_ai_solver.fem.model import Material, Model
from fem_ai_solver.fem.results import StaticSolveResult


@dataclass(slots=True)
class LayerBoundary:
    """Boundary polyline for one layer interface.

    The polyline must represent a single-valued y(x) profile with monotonically
    increasing x, so we can evaluate interface elevations by interpolation.
    """

    points: list[tuple[float, float]]


@dataclass(slots=True)
class GeotechLayer:
    """A geological layer bounded by top and bottom interfaces."""

    name: str
    material: Material
    top_boundary: LayerBoundary
    bottom_boundary: LayerBoundary


@dataclass(slots=True)
class PointOfInterest:
    """Named point used for displacement extraction (e.g., A/B in course tasks)."""

    name: str
    x: float
    y: float


@dataclass(slots=True)
class GeotechTemplateInput:
    """Input contract for one 2D geotechnical template run."""

    layers: list[GeotechLayer]
    mesh_target_size: float = 1.0
    top_line_load: float = 0.0
    fix_bottom_ux: bool = True
    fix_bottom_uy: bool = True
    constrain_lateral_ux: bool = True
    points_of_interest: list[PointOfInterest] = field(default_factory=list)
    backend: str = "python"
    thickness: float = 1.0
    area_tolerance: float = 1e-14


@dataclass(slots=True)
class GeotechPointResult:
    """Nearest-node displacement result for one named point."""

    name: str
    target_x: float
    target_y: float
    node_id: int
    node_x: float
    node_y: float
    ux: float
    uy: float
    distance: float


@dataclass(slots=True)
class GeotechOutputFiles:
    """Output artifacts generated by one workflow run."""

    base_dir: Path
    summary_json: Path
    node_displacements_csv: Path
    element_results_csv: Path
    point_displacements_csv: Path
    ux_cloud_svg: Path
    uy_cloud_svg: Path
    von_mises_cloud_svg: Path


@dataclass(slots=True)
class GeotechTemplateResult:
    """High-level geotechnical workflow result."""

    model: Model
    solve_result: StaticSolveResult
    point_results: list[GeotechPointResult]
    von_mises_by_element_id: dict[int, float]
    output_files: GeotechOutputFiles | None = None

